### ISSUE TITLE
Error Invalid Header Value

### ISSUE THREAD

**Issue by yash1441** [liamcottle/valorant.js#36]
Getting the following error upon usage of authrize()

```
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Cookie"
    at ClientRequest.setHeader (node:_http_outgoing:651:3)
    at new ClientRequest (node:_http_client:291:14)
    at Object.request (node:https:366:10)
    at RedirectableRequest._performRequest (/home/container/node_modules/follow-redirects/index.js:325:24)
    at new RedirectableRequest (/home/container/node_modules/follow-redirects/index.js:99:8)
    at Object.request (/home/container/node_modules/follow-redirects/index.js:531:14)
    at dispatchHttpRequest (/home/container/node_modules/@liamcottle/valorant.js/node_modules/axios/lib/adapters/http.js:202:25)
    at new Promise (<anonymous>)
    at httpAdapter (/home/container/node_modules/@liamcottle/valorant.js/node_modules/axios/lib/adapters/http.js:46:10)
    at dispatchRequest (/home/container/node_modules/@liamcottle/valorant.js/node_modules/axios/lib/core/dispatchRequest.js:53:10)
    at Axios.request (/home/container/node_modules/@liamcottle/valorant.js/node_modules/axios/lib/core/Axios.js:108:15)
    at Axios.<computed> [as put] (/home/container/node_modules/@liamcottle/valorant.js/node_modules/axios/lib/core/Axios.js:140:17)
    at Function.wrap [as put] (/home/container/node_modules/@liamcottle/valorant.js/node_modules/axios/lib/helpers/bind.js:9:15)
    at API.authorize (/home/container/node_modules/@liamcottle/valorant.js/src/api.js:98:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getStore (/home/container/commands/valo.js:1066:5)
    at async Object.execute (/home/container/commands/valo.js:679:33)
    at async Client.<anonymous> (/home/container/index.js:145:4) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}
```

The code was working for an year or so without any problem till 3 days ago when this error started occuring.

**Comment by Pinguu-dev** [comment]
@liamcottle

**Comment by SuppliedOrange** [comment]
### Here is a snippet by a user on a valorant app dev forum:

---------------

Recently Rito has decided to make almost all endpoints require `X-Riot-ClientPlatform` and `X-Riot-ClientVersion`.

[Techrism docs on the matter](https://valapidocs.techchrism.me/endpoint/fetch-content#client-platform)

# Client Platform
A string representing the platform of the client. Base-64 encoded JSON with the following fields:
```json
{
    "platformType": "PC",
    "platformOS": "Windows",
    "platformOSVersion": "10.0.19042.1.256.64bit",
    "platformChipset": "Unknown"
}
```
`ew0KCSJwbGF0Zm9ybVR5cGUiOiAiUEMiLA0KCSJwbGF0Zm9ybU9TIjogIldpbmRvd3MiLA0KCSJwbGF0Zm9ybU9TVmVyc2lvbiI6ICIxMC4wLjE5MDQyLjEuMjU2LjY0Yml0IiwNCgkicGxhdGZvcm1DaGlwc2V0IjogIlVua25vd24iDQp9`
is a value that works.

# Client Version
The version of the Valorant client. This can be obtained in a number of ways:
- Parsing the ShooterGame log at %LocalAppData%\VALORANT\Saved\Logs\ShooterGame.log
- Using the [Sessions](https://valapidocs.techchrism.me/endpoint/sessions) endpoint
- Using the third-party [Versions](https://dash.valorant-api.com/endpoints/version) endpoint

---------------

### What I do for client version:

The best way to go about it without having valorant running is using https://valorant-api.com/v1/version as mentioned in the last point.

My fork of valclient.js does the same in `./src/client.ts` https://github.com/SuppliedOrange/valclient.js
